### ISSUE TITLE
UUPMediaConverter CLI does not create ISO with latest desired version

### ISSUE THREAD

**Issue by Dhyfer1** [gus33000/UUPMediaCreator#142] opened 2023-01-13 03:27 UTC
Hi @gus33000 

I want to download the ISO file of Windows 11 Pro beta channel with the latest build to date (22623.1095) and for that I have entered the following command in UUPDownload:

`-s Professional -v 10.0.22623.1095 -t amd64 -r External -b Beta -c ni_release -e Professional -l en-US`

Then the files start downloading, and there is no problem on the download. All downloaded files are placed inside a new folder named **10.0.22623.1095.ni_release_svc_betaflt_prod1.221219-1229_amd64fre_542908aca3fd** and has a size of 2.87GB.

Then, when I use UUPMediaConverter (run as admin) to create the ISO with the following command:

`-u "C:\Users\diego\Downloads\win-x64\CLI\10.0.22623.1095.ni_release_svc_betaflt_prod1.221219-1229_amd64fre_542908aca3fd" -i "C:\Users\diego\Desktop\Windows11.iso" -e Professional -l en-US`

I ended up getting an ISO file with an older build (22621.1). I know that the "Update file integration (UUPMediaConverter)" function is not yet supported for Windows as indicated in the "Supported features by OS" table as can be seen in the Readme of this repository, that's why I end up with the ISO of a previous build? If so, and while waiting for a new update of UUPMediaCreator with the "Update file integration" function, how else can I create the ISO with the latest build with the files downloaded by UUPDownload?

**Comment by gus33000** [comment] 2023-01-13 06:30
Duplicate of #92

Yea you are missing the cumulative update, including the one faking the version number from 22621 to 22623 (this is fake yes) due to the same problem.

You can just check for updates once installed to get the cumulative updates or manually integrate updates yourself.

**Closed** 2023-01-13 06:30 UTC
